// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// الملف: firebase_options.dart
// المسار: firebase_options.dart
// الطبقة: جذر التطبيق
//
// ماذا يفعل؟
//   إعدادات Firebase المولّدة.
//
// ماذا بداخله؟
//   • DefaultFirebaseOptions
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
//// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// كلاس default Firebase إعدادات.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
  /// دالة switch.
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        /// دالة unsupported خطأ.
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        /// دالة unsupported خطأ.
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        /// دالة unsupported خطأ.
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        /// دالة unsupported خطأ.
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// حقل: ويب.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_KDyqeC7tHstBuH5kLZJiRjI3Zk8P3dM',
    appId: '1:698540357194:web:b07fdb2195fd936ea498b3',
    messagingSenderId: '698540357194',
    projectId: 'farmassistant-54d84',
    authDomain: 'farmassistant-54d84.firebaseapp.com',
    storageBucket: 'farmassistant-54d84.firebasestorage.app',
    measurementId: 'G-GEVCV01VS5',
  );

  /// حقل: android.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuDtD5hSNQc7Hm8bGhu8goeYtOCR3Xr0I',
    appId: '1:698540357194:android:e3380e1e65a0cf6aa498b3',
    messagingSenderId: '698540357194',
    projectId: 'farmassistant-54d84',
    storageBucket: 'farmassistant-54d84.firebasestorage.app',
  );

  /// حقل: ios.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQh1ZnEH4sPJb9e8dvogTtODHVoZThmPs',
    appId: '1:698540357194:ios:5a8217f714a0a20ea498b3',
    messagingSenderId: '698540357194',
    projectId: 'farmassistant-54d84',
    storageBucket: 'farmassistant-54d84.firebasestorage.app',
    iosBundleId: 'com.farmassistant.app',
  );

}